export const vatRate = {
  AT: { country: 'Austria', value: 20 },
  BE: { country: 'Belgium', value: 21 },
  BG: { country: 'Bulgaria', value: 20 },
  GB: { country: 'Great Britain', value: 20 },
  DE: { country: 'Germany', value: 19 },
  GR: { country: 'Greece', value: 23 },
  DK: { country: 'Denmark', value: 25 },
  EE: { country: 'Estonia', value: 20 },
  IE: { country: 'Ireland', value: 23 },
  ES: { country: 'Spain', value: 21 },
  IT: { country: 'Italy', value: 22 },
  CY: { country: 'Cyprus', value: 19 },
  LV: { country: 'Latvia', value: 21 },
  LT: { country: 'Lithuania', value: 21 },
  LU: { country: 'Luxembourg', value: 17 },
  MT: { country: 'Malta', value: 18 },
  PL: { country: 'Poland', value: 23 },
  PT: { country: 'Portugal', value: 23 },
  RO: { country: 'Romania', value: 24 },
  SK: { country: 'Slovakia', value: 20 },
  SI: { country: 'Slovenia', value: 22 },
  HU: { country: 'Hungary', value: 27 },
  FI: { country: 'Finland', value: 24 },
  FR: { country: 'France', value: 20 },
  NL: { country: 'Holland', value: 21 },
  HR: { country: 'Croatia', value: 25 },
  CZ: { country: 'Czech Republic', value: 21 },
  SE: { country: 'Sweden', value: 25 },
};
